/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencentbox_gamepad_MainService */

#ifndef _Included_com_tencentbox_gamepad_MainService
#define _Included_com_tencentbox_gamepad_MainService
#ifdef __cplusplus
extern "C" {
JNIEXPORT jboolean JNICALL Java_com_tencentbox_gamepad_MainService_nativeStartService(
		JNIEnv *, jobject);

JNIEXPORT jboolean JNICALL Java_com_tencentbox_gamepad_MainService_nativePauseService(
		JNIEnv *, jobject);

JNIEXPORT jboolean JNICALL Java_com_tencentbox_gamepad_MainService_nativeResumeService(
		JNIEnv *, jobject);

JNIEXPORT jboolean JNICALL Java_com_tencentbox_gamepad_MainService_nativeSetOperatingMap(
		JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint, jint, jint,
		jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint,
		jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

JNIEXPORT jboolean JNICALL Java_com_tencentbox_gamepad_MainService_nativeSetBlacklist(
		JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint, jint, jint,
		jint, jint, jint, jint, jint, jint, jint, jint, jint);

JNIEXPORT jboolean JNICALL Java_com_tencentbox_gamepad_MainService_nativeSetSensity(
		JNIEnv *, jobject, jstring, jint, jint);
}
#endif
#endif
